---
title: "HW 2"
format: pdf
editor: visual
---

```{r}
#| message: false
#| echo: false
library(tidyverse)
```

## Question 1 (4 points)

How far, in Kilometres, is Andy's office at MSU (in Wilson Hall) from his sabbatical office at Griffith University (Nathan Campus). Use naive Euclidean distance, chordal distance, and geodesic distance.

Note: this will require that you find approximate latitude and longitude coordinates for these locations.

## Question 2 

### Part 1 (3 points)

Simulate and visualize a marked point process (with 2 or more discrete levels) that has complete spatial homogeneity.

### Part 2 (3 points)

Implement one or more hypothesis test for complete spatial homogeneity. Summarize the results of this test. Make sure to account for the marked result.

### Part 3 (3 points)

Create an estimated intensity surface for your point process (and overlay the observed point). Add a caption to the figure that clearly describes the results and how to interpret the intensity function.


## Question 3 

### Part 1 (3 points)

Simulate and visualize a point process that does not have complete spatial homogeneity.

### Part 2 (3 points)

Implement one or more hypothesis test for complete spatial homogeneity. Summarize the results of this test. 

### Part 3 (3 points)

Create an estimated intensity surface for your point process (and overlay the observed point). Add a caption to the figure that clearly describes the results and how to interpret the intensity function.
